import { SectionConfig } from "./types";

export const dashboardConfig: SectionConfig[] = [
  {
    id: "home",
    name: "Home",
    type: "mixed",
    languages: ["en", "sv", "fr"],
    fields: [
      {
        id: "name",
        label: "Name",
        type: "text",
        required: true,
        placeholder: "Enter name",
      },
      {
        id: "tagline",
        label: "Tagline",
        type: "text",
        required: false,
        placeholder: "Enter hero tagline",
      },
      {
        id: "Image",
        label: "Hero Image",
        type: "image",
        required: true,
        placeholder: "image url",
      },
      {
        id: "profileImage",
        label: "Profile Image",
        type: "image",
        required: true,
        placeholder: "Add Profile Picture",
      },
      {
        id: "aboutTitle",
        label: "About Title",
        type: "text",
        required: true,
        placeholder: "Enter about title",
      },
      {
        id: "description",
        label: "Description",
        type: "textarea",
        required: true,
        placeholder: "Enter description",
      },
      {
        id: "aboutButtonText",
        label: "About Button Text",
        type: "text",
        required: true,
        placeholder: "Enter about button text",
      },
      {
        id: "listenTitle",
        label: "Listen Title",
        type: "text",
        required: false,
        placeholder: "Enter listen title",
      },
      {
        id: "listenButtonText",
        label: "Listen Button Text",
        type: "text",
        required: true,
        placeholder: "Enter listen button text",
      },
      {
        id: "SecondImage",
        label: "Second Home Image",
        type: "image",
        required: true,
        placeholder: "Add a second image",
      },
      {
        id: "youtubeUrl",
        label: "YouTube URL",
        type: "text",
        required: true,
        placeholder:
          "https://www.youtube.com/watch?v=... eller https://youtu.be/...",
      },
    ],
  },
  {
    id: "schedule",
    name: "Schedule",
    type: "mixed",
    languages: ["en", "sv", "fr"],
    fields: [
      {
        id: "scheduleTitle",
        label: "Schedule Title",
        type: "text",
        required: true,
        placeholder: "Enter schedule title",
      },
      {
        id: "ScheduleBookTitle",
        label: "Schedule Book Title",
        type: "text",
        required: true,
        placeholder: "Enter schedule book title",
      },
      {
        id: "ScheduleBookDesc",
        label: "Schedule Book Description",
        type: "textarea",
        required: true,
        placeholder: "Enter schedule book description",
      },
      {
        id: "ScheduöeBookEmail",
        label: "Schedule Book Email",
        type: "text",
        required: true,
        placeholder: "Enter schedule book email",
      },
      {
        id: "ScheduleBookPhone",
        label: "Schedule Book Phone",
        type: "text",
        required: true,
        placeholder: "Enter schedule book phone",
      },
    ],
    listItemConfig: {
      fields: [
        {
          id: "id",
          label: "ID",
          type: "text",
          required: true,
          placeholder: "Unique ID (e.g., '1')",
        },
        {
          id: "title",
          label: "Title",
          type: "text",
          required: true,
          placeholder: "Event title (e.g., 'Lohengrin')",
        },
        {
          id: "location",
          label: "Location",
          type: "text",
          required: true,
          placeholder: "Event location (e.g., 'Malmö Opera')",
        },
        {
          id: "time",
          label: "Time",
          type: "text",
          required: false,
          placeholder: "Event time (e.g., '16:00')",
        },
        {
          id: "description",
          label: "Description",
          type: "textarea",
          required: false,
          placeholder: "Event description",
        },
        {
          id: "startDate",
          label: "Start Date",
          type: "date",
          required: false,
          nestedFields: [
            {
              id: "day",
              label: "Day",
              type: "number",
              required: false,
              placeholder: "Day",
            },
            {
              id: "month",
              label: "Month",
              type: "text",
              required: false,
              placeholder: "Month (e.g., 'October')",
            },
            {
              id: "year",
              label: "Year",
              type: "number",
              required: false,
              placeholder: "Year",
            },
          ],
        },
      ],
    },
  },
  {
    id: "media",
    name: "Media",
    type: "mixed",
    languages: ["en", "sv", "fr"],
    fields: [
      {
        id: "mediaTitle",
        label: "Media Title",
        type: "text",
        required: true,
        placeholder: "Enter media title",
      },
      {
        id: "mediaSubtitle",
        label: "Media Subtitle",
        type: "text",
        required: true,
        placeholder: "Enter media subtitle",
      },
      {
        id: "videoSectionTitle",
        label: "VideoSection Title",
        type: "text",
        required: false,
        placeholder: "Videos Section Title",
      },
      {
        id: "musicSectionTitle",
        label: "Music Section Title",
        type: "text",
        required: false,
        placeholder: "Music Section Title",
      },
      {
        id: "gallerySectionTitle",
        label: "Gallery Section Title",
        type: "text",
        required: false,
        placeholder: "Gallery Section Title",
      },
    ],
    listItemConfigs: {
      videos: {
        fields: [
          {
            id: "youtubeUrl",
            label: "YouTube URL",
            type: "text",
            required: true,
            placeholder:
              "https://www.youtube.com/watch?v=... eller https://youtu.be/...",
          },
          {
            id: "title",
            label: "Video Title",
            type: "text",
            required: true,
            placeholder: "Video title (e.g., 'Stars')",
          },
          {
            id: "description",
            label: "Description",
            type: "textarea",
            required: false,
            placeholder: "Video description",
          },
        ],
      },
      music: {
        fields: [
          {
            id: "spotifyUrl",
            label: "Spotify URL",
            type: "text",
            required: true,
            placeholder:
              "https://open.spotify.com/track/... eller https://open.spotify.com/album/... eller https://open.spotify.com/playlist/...",
          },
          // Valfritt: om du vill ha titel (ser ut som den är kommenterad i ditt exempel)
          {
            id: "title",
            label: "Title",
            type: "text",
            required: false,
            placeholder:
              "Track/Album/Playlist title (e.g., 'Eric Schoeffler - Album')",
          },
        ],
      },
      gallery: {
        fields: [
          {
            id: "url",
            label: "Image URL",
            type: "image",
            required: true,
            placeholder: "Image URL or upload",
          },
          {
            id: "alt",
            label: "Alt Text",
            type: "text",
            required: true,
            placeholder: "Image description",
          },
        ],
      },
    },
  },
  {
    id: "about",
    name: "About",
    type: "mixed",
    languages: ["en", "sv", "fr"],
    fields: [
      {
        id: "aboutTitle",
        label: "About Title",
        type: "text",
        required: true,
        placeholder: "Enter about title",
      },
      {
        id: "aboutText",
        label: "About Text",
        type: "textarea",
        required: true,
        placeholder: "Enter about text",
      },
      {
        id: "AboutImage",
        label: "About Image",
        type: "image",
        required: true,
        placeholder: "Enter about image",
      },
    ],
  },
];
