import { SectionConfig } from "./types";

export const dashboardConfig: SectionConfig[] = [
  {
    id: "hero",
    name: "Hero Section",
    type: "mixed",
    languages: ["en", "sv", "fr"],
    fields: [
      {
        id: "name",
        label: "Name",
        type: "text",
        required: true,
        placeholder: "Enter name",
      },
      {
        id: "tagline",
        label: "Tagline",
        type: "text",
        required: false,
        placeholder: "Enter hero tagline",
      },
      {
        id: "Image",
        label: "Hero Image",
        type: "image",
        required: true,
        placeholder: "image url",
      },
      {
        id: "profileImage",
        label: "Profile Image",
        type: "image",
        required: true,
        placeholder: "Add Profile Picture",
      },
      {
        id: "aboutTitle",
        label: "About Title",
        type: "text",
        required: true,
        placeholder: "Enter about title",
      },
      {
        id: "description",
        label: "Description",
        type: "textarea",
        required: true,
        placeholder: "Enter description",
      },
      {
        id: "aboutButtonText",
        label: "About Button Text",
        type: "text",
        required: true,
        placeholder: "Enter about button text",
      },
      {
        id: "listenTitle",
        label: "Listen Title",
        type: "text",
        required: false,
        placeholder: "Enter listen title",
      },
      {
        id: "listenButtonText",
        label: "Listen Button Text",
        type: "text",
        required: true,
        placeholder: "Enter listen button text",
      },
      {
        id: "SecondImage",
        label: "Second Home Image",
        type: "image",
        required: true,
        placeholder: "Add a second image",
      },
      {
        id: "youtubeUrl",
        label: "YouTube URL",
        type: "text",
        required: true,
        placeholder:
          "https://www.youtube.com/watch?v=... eller https://youtu.be/...",
      },
    ],
  },
  {
    id: "schedule",
    name: "Schedule",
    type: "mixed",
    languages: ["en", "sv", "fr"],
    fields: [
      {
        id: "scheduleTitle",
        label: "Schedule Title",
        type: "text",
        required: true,
        placeholder: "Enter schedule title",
      },
    ],
    listItemConfig: {
      fields: [
        {
          id: "id",
          label: "ID",
          type: "text",
          required: true,
          placeholder: "Unique ID (e.g., '1')",
        },
        {
          id: "title",
          label: "Title",
          type: "text",
          required: true,
          placeholder: "Event title (e.g., 'Lohengrin')",
        },
        {
          id: "location",
          label: "Location",
          type: "text",
          required: true,
          placeholder: "Event location (e.g., 'Malmö Opera')",
        },
        {
          id: "time",
          label: "Time",
          type: "text",
          required: false,
          placeholder: "Event time (e.g., '16:00')",
        },
        {
          id: "description",
          label: "Description",
          type: "textarea",
          required: false,
          placeholder: "Event description",
        },
        {
          id: "startDate",
          label: "Start Date",
          type: "date",
          required: false,
          nestedFields: [
            {
              id: "day",
              label: "Day",
              type: "number",
              required: false,
              placeholder: "Day",
            },
            {
              id: "month",
              label: "Month",
              type: "text",
              required: false,
              placeholder: "Month (e.g., 'October')",
            },
            {
              id: "year",
              label: "Year",
              type: "number",
              required: false,
              placeholder: "Year",
            },
          ],
        },
      ],
    },
  },
];
